In [17]:

import pandas as pd

df = pd.read_csv(r"C:\\Contents\\Kaggle\\file_pe_headers.csv")

df.head()



Name  e_magic  e_cblp  e_cp  e_crlc  \
0  VirusShare_a878ba26000edaac5c98eff4432723b3    23117     144     3       0   
1  VirusShare_ef9130570fddc174b312b2047f5f4cf0    23117     144     3       0   
2  VirusShare_ef84cdeba22be72a69b198213dada81a    23117     144     3       0   
3  VirusShare_6bf3608e60ebc16cbcff6ed5467d469e    23117     144     3       0   
4  VirusShare_2cc94d952b2efb13c7d6bbe0dd59d3fb    23117     144     3       0   

   e_cparhdr  e_minalloc  e_maxalloc  e_ss  e_sp  ...  SectionMaxChar  \
0          4           0       65535     0   184  ...      3758096608   
1          4           0       65535     0   184  ...      3791650880   
2          4           0       65535     0   184  ...      3221225536   
3          4           0       65535     0   184  ...      3224371328   
4          4           0       65535     0   184  ...      3227516992   

   SectionMainChar  DirectoryEntryImport  DirectoryEntryImportSize  \
0                0                     7                       152   
1                0                    16                       311   
2                0                     6                       176   
3                0                     8                       155   
4                0                     2                        43   

   DirectoryEntryExport  ImageDirectoryEntryExport  ImageDirectoryEntryImport  \
0                     0                          0                      54440   
1                     0                          0                     262276   
2                     0                          0                      36864   
3                     0                          0                     356352   
4                     0                          0                      61440   

   ImageDirectoryEntryResource  ImageDirectoryEntryException  \
0                        77824                         73728   
1                       294912                             0   
2                        40960                             0   
3                      1003520                             0   
4                        73728                             0   

   ImageDirectoryEntrySecurity  
0                            0  
1                       346112  
2                            0  
3                     14109472  
4                        90624  

[5 rows x 79 columns]

In [4]:
df.columns

Index(['Name', 'e_magic', 'e_cblp', 'e_cp', 'e_crlc', 'e_cparhdr',
       'e_minalloc', 'e_maxalloc', 'e_ss', 'e_sp', 'e_csum', 'e_ip', 'e_cs',
       'e_lfarlc', 'e_ovno', 'e_oemid', 'e_oeminfo', 'e_lfanew', 'Machine',
       'NumberOfSections', 'TimeDateStamp', 'PointerToSymbolTable',
       'NumberOfSymbols', 'SizeOfOptionalHeader', 'Characteristics', 'Magic',
       'MajorLinkerVersion', 'MinorLinkerVersion', 'SizeOfCode',
       'SizeOfInitializedData', 'SizeOfUninitializedData',
       'AddressOfEntryPoint', 'BaseOfCode', 'ImageBase', 'SectionAlignment',
       'FileAlignment', 'MajorOperatingSystemVersion',
       'MinorOperatingSystemVersion', 'MajorImageVersion', 'MinorImageVersion',
       'MajorSubsystemVersion', 'MinorSubsystemVersion', 'SizeOfHeaders',
       'CheckSum', 'SizeOfImage', 'Subsystem', 'DllCharacteristics',
       'SizeOfStackReserve', 'SizeOfStackCommit', 'SizeOfHeapReserve',
       'SizeOfHeapCommit', 'LoaderFlags', 'NumberOfRvaAndSizes', 'Malware',
       '

In [5]:
X = df.drop(['Name','Malware' ], axis = 1).values

In [6]:
type(X)

numpy.ndarray

In [7]:
X[0]

array([2.31170000e+04, 1.44000000e+02, 3.00000000e+00, 0.00000000e+00,
       4.00000000e+00, 0.00000000e+00, 6.55350000e+04, 0.00000000e+00,
       1.84000000e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       6.40000000e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.48000000e+02, 3.44040000e+04, 6.00000000e+00, 1.23651236e+09,
       0.00000000e+00, 0.00000000e+00, 2.40000000e+02, 3.40000000e+01,
       5.23000000e+02, 8.00000000e+00, 0.00000000e+00, 5.47840000e+04,
       1.89440000e+05, 0.00000000e+00, 5.13160000e+04, 4.09600000e+03,
       4.29496730e+09, 4.09600000e+03, 5.12000000e+02, 6.00000000e+00,
       0.00000000e+00, 6.00000000e+00, 0.00000000e+00, 5.00000000e+00,
       2.00000000e+00, 1.02400000e+03, 2.95281000e+05, 2.74432000e+05,
       2.00000000e+00, 3.28320000e+04, 5.24288000e+05, 8.19200000e+03,
       1.04857600e+06, 4.09600000e+03, 0.00000000e+00, 1.60000000e+01,
       0.00000000e+00, 0.00000000e+00, 6.00000000e+00, 0.00000000e+00,
      

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X = StandardScaler().fit_transform(X)

In [9]:
X[0]

array([ 0.        , -0.03506542, -0.04751096, -0.04054457, -0.03860147,
       -0.04043704,  0.14886744, -0.01635299, -0.0339818 , -0.02924235,
       -0.05893017, -0.05586989, -0.05329558, -0.05604821, -0.09271628,
       -0.08930667,  0.39409703,  2.55673514,  0.46510526, -0.16089899,
       -0.05112382, -0.05882497,  2.30985335, -0.5806138 ,  2.55673516,
       -0.07860642, -0.28822308, -0.02845818, -0.02821847, -0.00875967,
       -0.07360337, -0.01841394, -0.05817289, -0.22669255, -0.33481231,
       -0.01888407, -0.02217824, -0.03722535, -0.04207791,  0.28341472,
       -0.0129841 , -0.0482971 , -0.23304028, -0.03944348, -0.35502553,
        0.89475788, -0.39910304,  0.00791826, -0.01549748, -0.03432252,
       -0.02379985, -0.01055405, -0.74903275, -0.09913793,  0.46517515,
       -0.85505526,  0.        , -0.04763644,  0.        , -0.05380353,
        0.        , -0.06366286,  0.        , -0.03053373,  0.        ,
       -0.07891185,  0.        ,  1.01441302,  0.        ,  0.11

In [10]:
len(X[0])

77

In [11]:
pca = PCA()
Xdash = pca.fit_transform(X)


In [12]:
Xdash[0]

array([-1.16886290e-01, -7.15480741e-02,  3.16916194e+00,  1.60217942e+00,
       -1.08518997e+00, -4.48054756e-01,  4.62141076e-01, -1.92644812e-01,
       -3.77161530e-01, -5.67311951e-01,  4.02792196e-02,  5.69811591e-01,
       -6.25592903e-01,  1.86680113e+00, -1.21539054e-01, -3.42152826e-01,
       -1.95190544e-01, -2.33391969e-01, -3.45014025e-02,  3.55379220e-01,
       -2.35352980e-02,  5.90454242e-02, -9.22855437e-03,  6.23175910e-03,
        9.44316297e-02, -4.97347560e-01,  4.81316803e-01,  1.84736302e-01,
       -7.96710641e-01,  6.61878639e-01, -9.20345307e-01, -1.40835671e-01,
        1.99376285e-01, -3.49545323e-01,  1.03005921e-01, -3.45892793e-01,
       -1.33624714e-01, -8.24697306e-01, -1.74076538e-01, -4.21941811e-02,
        4.41508520e-01, -3.45017429e-02,  5.88588077e-02,  3.46669724e-01,
        8.85422333e-02, -1.50076127e-02,  3.71721361e-02,  9.95104534e-02,
        2.97609640e-02, -1.72450384e-01,  2.47519524e-01, -4.92508875e-01,
       -9.31538886e-02, -

In [14]:
pca.explained_variance_ratio_

array([1.13714096e-01, 6.04526312e-02, 5.35847638e-02, 4.95286930e-02,
       4.08242868e-02, 3.43687925e-02, 3.32004002e-02, 3.01112226e-02,
       2.86901095e-02, 2.81624164e-02, 2.54807940e-02, 2.38845548e-02,
       2.22696648e-02, 2.05755591e-02, 1.82485433e-02, 1.73648310e-02,
       1.66649078e-02, 1.63647194e-02, 1.52683994e-02, 1.46357930e-02,
       1.45790542e-02, 1.45535760e-02, 1.44699413e-02, 1.44154480e-02,
       1.42948516e-02, 1.39221004e-02, 1.35338124e-02, 1.33766277e-02,
       1.32896667e-02, 1.23472302e-02, 1.20507834e-02, 1.15452214e-02,
       1.13731313e-02, 1.10939084e-02, 1.07062189e-02, 1.01649154e-02,
       9.90148375e-03, 9.61478385e-03, 9.17627698e-03, 9.04802544e-03,
       8.66332999e-03, 6.94752252e-03, 6.84216033e-03, 6.48244001e-03,
       5.95005317e-03, 5.91335216e-03, 5.41615029e-03, 5.10640740e-03,
       4.83543074e-03, 4.45888820e-03, 4.29104432e-03, 3.82076025e-03,
       3.79864324e-03, 3.24146447e-03, 3.18558571e-03, 2.67004617e-03,
      

In [16]:
sum(pca.explained_variance_ratio_[:40])

0.9068522354673683